### PR TITLE
add resolution for reason

### PR DESCRIPTION
**Pull request by idkjs**
Greetings, @ulrikstrid.

I had to add resolutions for easy/ocaml and disable warning `16` for this run. Those changes are here  if you want them.

At this point, when you get to the test screen in the browser, both options get you an `Unhandled server error` message.

Screenshot 2021-07-07 at 20 51 36

Maybe there is some additional step you might tell me about.

Thanks for sharing, sir.

### CODE REVIEW

**Comment by anmonteiro** [comment]
Why don’t you use the officially released `@opam/reason` instead of a resolution?

**Comment by idkjs** [comment]
> Why don’t you use the officially released `@opam/reason` instead of a resolution?

Did not know it was good. I will try it an update. Thanks for the heads up.

Doesn't work.

```sh
 No package matching:

  oidc -> @reason-native-web/morph -> @esy-ocaml/reason -> @opam/result@=opam:1.2.0
  
  Versions available:
  
    @opam/result@opam:1.5
    @opam/result@opam:1.4
    @opam/result@opam:1.3
    @opam/result@opam:1.2
    @opam/result@opam:1.1
    @opam/result@opam:1.02.0
```

This would mean that `morph` is relying on `@esy-ocaml/reason` which needs `@opam/result@=opam:1.2.0` and that `esy` cant find a solution for `opam/result` that both `@opam/reason` and  `@esy-ocaml/reason` can use. Is that right?

**Comment by ulrikstrid** [comment]
The solution to that problem is to change from morph to Dream probably.

**Comment by idkjs** [comment]
> The solution to that problem is to change from morph to Dream probably.

Ok. In the mean time. I tried changing morph to `opam/reason` and `morph` works but then you get a conflict in some other file that I do not remember at this point, when you try to use that version here. Doable, i think, just need to work it.

**Comment by anmonteiro** [comment]
Gonna close this one as outdated.

**Pull request closed without merging**
